version: "3.5"

services:
  front:
    image: node:12.16.1
    volumes:
      - .:/jobboard
    working_dir: "/jobboard/apps/front"
    user: ${CURRENT_UID}
    ports:
      - 8000:8000
    command: "yarn dev"

  storybook:
    image: node:12.16.1
    volumes:
      - .:/jobboard
    working_dir: "/jobboard/apps/front"
    user: ${CURRENT_UID}
    ports:
      - 8010:6006
    command: "yarn storybook"

  admin:
    image: node:12.16.1
    volumes:
      - ./:/jobboard
    working_dir: "/jobboard/apps/admin"
    user: ${CURRENT_UID}
    ports:
      - 8002:3000
    command: "yarn run start"
    depends_on:
      - api
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - BROWSER=none
      - CI=true

  api:
    image: node:12.16.1
    volumes:
      - .:/jobboard
    working_dir: "/jobboard/apps/api"
    user: ${CURRENT_UID}
    ports:
      - 8001:3001
    env_file:
      - ./config/${NODE_ENV}.env
    depends_on:
      - postgres
    command: "yarn dev"

  postgres:
    image: postgres:12.2
    volumes:
      - jobboard-pgData:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./config/${NODE_ENV}.env

volumes:
  jobboard-pgData:
